// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJP-xXTemAK8V9W_WLuMqMejr2jHeC9EY',
    appId: '1:271799014388:web:86c23fb2a181d96ea6dfa1',
    messagingSenderId: '271799014388',
    projectId: 'authcafe-b98c3',
    authDomain: 'authcafe-b98c3.firebaseapp.com',
    storageBucket: 'authcafe-b98c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qURrN4G2hklTuJMYCoEqfJP-ox-Wi40',
    appId: '1:271799014388:android:c6739b0674cb5fd6a6dfa1',
    messagingSenderId: '271799014388',
    projectId: 'authcafe-b98c3',
    storageBucket: 'authcafe-b98c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwi79nwvK5ZzETkyLrqS1kkkH9rsdWi8w',
    appId: '1:271799014388:ios:95cf2b1d3722e73da6dfa1',
    messagingSenderId: '271799014388',
    projectId: 'authcafe-b98c3',
    storageBucket: 'authcafe-b98c3.appspot.com',
    iosBundleId: 'com.example.netCafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwi79nwvK5ZzETkyLrqS1kkkH9rsdWi8w',
    appId: '1:271799014388:ios:4aaf70d080f5573aa6dfa1',
    messagingSenderId: '271799014388',
    projectId: 'authcafe-b98c3',
    storageBucket: 'authcafe-b98c3.appspot.com',
    iosBundleId: 'com.example.netCafeApp.RunnerTests',
  );
}
